import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import HomeStyles from '@/styles/HomeStyles.module.css'
import StyledLink from '@/components/StyledLink'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={HomeStyles.container}>
        <div className={HomeStyles.btn}>
          <StyledLink href='/' linkText='Enter' />
        </div>
      </div>
    </>
  )
}
