import Head from 'next/head'

import { Inter } from 'next/font/google'
import HomeStyles from '@/styles/HomeStyles.module.scss'
import StyledLink from '@/components/StyledLink'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className={HomeStyles.container}>
          <div className={HomeStyles.row}>
            <div className={HomeStyles.column}>
              <h1 className={HomeStyles.dancer}>DANCER</h1>
            </div>
            <div className={HomeStyles.column}>
              <h1 className={HomeStyles.choreographer}>CHOREOGRAPHER</h1>
            </div>
            <div className={HomeStyles.column}>
              <h1 className={HomeStyles.coach}>DANCE  EDUCATOR</h1>
              
            </div>
          </div>
          <div className={HomeStyles.btn}>
            <StyledLink href='/about' label='Enter' isEnter />
          </div>
      </div>
    </>
  )
}
